activation: !!python/name:torch.nn.functional.log_softmax ''
conceptizator: identity_bool
explainer_hidden:
- 10
- 10
l1: 0.001
loss: !!python/object:torch.nn.modules.loss.CrossEntropyLoss
  _backward_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _buffers: !!python/object/apply:collections.OrderedDict
  - - - weight
      - null
  _forward_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _is_full_backward_hook: null
  _load_state_dict_post_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _modules: !!python/object/apply:collections.OrderedDict
  - []
  _non_persistent_buffers_set: !!set {}
  _parameters: !!python/object/apply:collections.OrderedDict
  - []
  _state_dict_hooks: !!python/object/apply:collections.OrderedDict
  - []
  ignore_index: -100
  label_smoothing: 0.0
  reduction: mean
  training: true
lr: 0.01
n_classes: 2
n_concepts: 33
optimizer: adamw
temperature: 0.6
